version: "3"
services:
    web:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../html:/www
            - ./data/logs:/logs
        links:
            - server
        networks:
            - network

    server:
        build:
            context: .
            dockerfile: Dockerfile
        stop_grace_period: 0s
        environment:
            PORT: 3333
            DATABASE: ${SKYCHAT2_DB}
            DATABASE_USER: ${SKYCHAT2_DB_USER}
            DATABASE_PASSWORD: ${SKYCHAT2_DB_PASSWORD}
        volumes:
            - ./data:/data
            - ../:/app
        links:
            - db
        networks:
            - network
    db:
        image: postgres:16-alpine
        restart: always
        environment:
            POSTGRES_DB: ${SKYCHAT2_DB}
            POSTGRES_USER: ${SKYCHAT2_DB_USER}
            POSTGRES_PASSWORD: ${SKYCHAT2_DB_PASSWORD}
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        networks:
            - network

networks:
    network:
        driver: bridge
